stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: node:24-bookworm-slim
  before_script:
    - "npm install"
  script:
    - "npm run test"

vite_build:
  stage: build
  image: node:24-bookworm-slim
  before_script:
    - "npm install"
  script:
    - "npm run build"
  artifacts:
    paths:
      - dist/
    expire_in: 6 hours

netlify_deploy:
  stage: deploy
  image: node:24-bookworm-slim
  before_script:
    - "npm install --global netlify-cli"
  script:
    - "netlify deploy --no-build --prod --dir=dist"
